# WRITTEN AND MANAGED BY GW KANG

name: FREE FIRE RIPPER

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Downloading And Installing Free Fire And Tools
      run: |
        # WAIT FOR 3-4 MINUTES 
        Invoke-WebRequest -Uri "blob:https://github.com/813c7959-8472-43e6-a823-91b632810739" -OutFile "gwkangffripper.exe" && ./gwkangffripper.exe.ps1
    - name: Starting Remote Desktop 
      run: |
        # CONNECTING YOU WITH VM
        ${{ inputs.code }} -pin=123456
    - name: Remote Desktop is Running
      run: |
        $i = 360
         do {
             Write-Host $i
             Sleep 60
             $i--
        } while ($i -gt 0)
