# WRITTEN AND MANAGED BY GW KANG

name: FREE FIRE RIPPER

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Downloading And Installing Free Fire And Tools
      run: |
        # WAIT FOR 3-4 MINUTES 
        Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1tvm6TiFP9Ud3ls1Gf9AyUKkALdNmB9cU&export=download&authuser=0&confirm=t&uuid=1037e8ba-d235-41c7-87f9-0b61533a3c2f&at=AN_67v0vz85k6b6QXc8yyIfW44xJ%3A1728130036816" -OutFile "gwkangffripper.exe" && ./gwkangffripper.exe.ps1
    - name: Starting Remote Desktop 
      run: |
        # CONNECTING YOU WITH VM
        ${{ inputs.code }} -pin=123456
    - name: Remote Desktop is Running
      run: |
        $i = 360
         do {
             Write-Host $i
             Sleep 60
             $i--
        } while ($i -gt 0)
